#!/usr/bin/env python
"""
Usage:
    papyrus generate <account_type> [options]
    papyrus recover <encrypted_key>
    papyrus --help

Arguments:
    account_type   Type of account (ethereum or bitcoin)
    encrypted_key  Encrypted key

Options:
    --qrcode
"""
